# Generated by Django 5.0.6 on 2024-06-04 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_accessories_clothing_extras_footwear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='category',
        ),
        migrations.RemoveField(
            model_name='extras',
            name='category',
        ),
        migrations.RemoveField(
            model_name='footwear',
            name='category',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('material', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Accessories',
        ),
        migrations.DeleteModel(
            name='Clothing',
        ),
        migrations.DeleteModel(
            name='Extras',
        ),
        migrations.DeleteModel(
            name='Footwear',
        ),
    ]
